import { NextRequest, NextResponse } from "next/server";
import fs from "fs";
import path from "path";

const STORAGE_ROOT = path.resolve(process.cwd(), ".local_storage");

// Keys generated by the upload route look like "draft/1724.._file.pdf".
// Reject anything that is not a plain relative storage key.
const SAFE_KEY_PATTERN = /^[a-zA-Z0-9][a-zA-Z0-9/_\-.]{0,500}$/;

function resolveStoragePath(key: string): string | null {
  if (!SAFE_KEY_PATTERN.test(key)) return null;

  const resolved = path.resolve(STORAGE_ROOT, key);
  const rootWithSep = STORAGE_ROOT.endsWith(path.sep)
    ? STORAGE_ROOT
    : STORAGE_ROOT + path.sep;

  if (resolved !== STORAGE_ROOT && !resolved.startsWith(rootWithSep)) {
    return null;
  }
  return resolved;
}

export async function GET(req: NextRequest) {
  const { searchParams } = new URL(req.url);
  const key = searchParams.get("key");

  if (!key) {
    return NextResponse.json({ error: "Key is required" }, { status: 400 });
  }

  const filePath = resolveStoragePath(key);
  if (!filePath) {
    return NextResponse.json({ error: "Invalid storage key" }, { status: 400 });
  }

  if (!fs.existsSync(filePath) || !fs.statSync(filePath).isFile()) {
    return NextResponse.json({ error: "File not found" }, { status: 404 });
  }

  const buffer = fs.readFileSync(filePath);
  const ext = path.extname(filePath).toLowerCase();
  let contentType = "application/octet-stream";

  if (ext === ".pdf") contentType = "application/pdf";
  else if (ext === ".jpg" || ext === ".jpeg") contentType = "image/jpeg";
  else if (ext === ".png") contentType = "image/png";

  // Never inline arbitrary files: force download for non-renderable types and
  // prevent the response from being used as an XSS/HTML carrier.
  const inlineTypes = ["application/pdf", "image/jpeg", "image/png"];
  const disposition = inlineTypes.includes(contentType) ? "inline" : "attachment";

  const safeName = path.basename(filePath).replace(/[^\w.\-ก-๙]/g, "_");

  return new NextResponse(buffer, {
    headers: {
      "Content-Type": contentType,
      "Content-Disposition": `${disposition}; filename="${safeName}"`,
      "X-Content-Type-Options": "nosniff",
      "Content-Security-Policy": "default-src 'none'; style-src 'unsafe-inline'",
    },
  });
}
