import { BudgetProposal, AttachmentItem, ReviewComment } from "../../types/budget";
import { Full6StepAnalysis, KKUBudgetForm8Sections, Step6NeutralSpecResult } from "../../types/ai";

/**
 * 40 Comprehensive Mock Budget Proposals for SpecWise AI (KKU Fiscal Year 2570)
 * Covering all faculties, categories, statuses, alert levels, budget ranges, and 6-step AI analyses.
 */

export const MOCK_PROPOSALS: BudgetProposal[] = [
  // ==========================================
  // หมวดที่ 1: ครุภัณฑ์คอมพิวเตอร์และระบบเครือข่าย (10 รายการ)
  // ==========================================
  {
    id: "req-001",
    code: "REQ-2570-001",
    title: "เครื่องคอมพิวเตอร์ สำหรับงานประมวลผล ด้าน Data Science และ AI",
    faculty: "คณะวิทยาศาสตร์",
    department: "สาขาวิชาเคมี",
    requesterId: "emp-001",
    requesterName: "ดร.สมชาย แก้วกล้า",
    requesterEmail: "somchai.k@kku.ac.th",
    status: "AI_ANALYZED",
    fiscalYear: 2570,
    category: "ครุภัณฑ์คอมพิวเตอร์",
    totalBudgetBaht: 500000,
    quantity: 10,
    unit: "เครื่อง",
    unitPriceBaht: 50000,
    standardMatched: true,
    standardName: "เครื่องคอมพิวเตอร์ สำหรับงานประมวลผล แบบที่ 1 *(จอแสดงภาพขนาดไม่น้อยกว่า 23 นิ้ว)",
    alertLevel: "AMBER_ALERT",
    createdAt: "2026-08-25T09:30:00Z",
    updatedAt: "2026-08-26T14:30:00Z",
    attachments: [
      {
        id: "att-001-1",
        type: "PHOTO_EQUIPMENT",
        fileName: "lab_sc6401_workstation.jpg",
        fileSize: 2450000,
        contentType: "image/jpeg",
        storageKey: "photos/req-001-lab.jpg",
        uploadedAt: "2026-08-25T10:00:00Z",
      },
      {
        id: "att-001-2",
        type: "QUOTATIONS_3_PDF",
        fileName: "merged_3_quotations_datascience.pdf",
        fileSize: 4800000,
        contentType: "application/pdf",
        storageKey: "quotations/req-001-3quotes.pdf",
        uploadedAt: "2026-08-25T10:05:00Z",
      },
    ],
    reviewComments: [
      {
        id: "comm-001-1",
        authorId: "emp-002",
        authorName: "นายประเสริฐ รักงาน",
        authorRole: "DEPT_VERIFIER",
        content: "รายละเอียดคุณลักษณะเฉพาะเชิงหน้าที่ครบถ้วน ตรวจสอบใบเสนอราคา 3 รายเปรียบเทียบเรียบร้อยแล้ว",
        action: "COMMENT",
        createdAt: "2026-08-26T14:30:00Z",
      },
    ],
  },
  {
    id: "req-002",
    code: "REQ-2570-002",
    title: "เครื่องคอมพิวเตอร์พกพา (Notebook) สำหรับงานวิจัยภาคสนามและการเก็บข้อมูลวิจัย",
    faculty: "คณะวิทยาศาสตร์",
    department: "สาขาวิชาเคมี",
    requesterId: "emp-001",
    requesterName: "ดร.สมชาย แก้วกล้า",
    requesterEmail: "somchai.k@kku.ac.th",
    status: "APPROVED",
    fiscalYear: 2570,
    category: "ครุภัณฑ์คอมพิวเตอร์",
    totalBudgetBaht: 190000,
    quantity: 5,
    unit: "เครื่อง",
    unitPriceBaht: 38000,
    standardMatched: true,
    standardName: "เครื่องคอมพิวเตอร์พกพา (Notebook) สำหรับงานประมวลผล",
    alertLevel: "GREEN_MATCH",
    createdAt: "2026-08-20T08:00:00Z",
    updatedAt: "2026-08-22T16:00:00Z",
    attachments: [
      {
        id: "att-002-1",
        type: "SPEC_PDF",
        fileName: "notebook_field_spec.pdf",
        fileSize: 1200000,
        contentType: "application/pdf",
        storageKey: "specs/req-002-spec.pdf",
        uploadedAt: "2026-08-20T08:30:00Z",
      },
    ],
    reviewComments: [
      {
        id: "comm-002-1",
        authorId: "emp-003",
        authorName: "ศ.ดร.วิโรจน์ วิเศษ",
        authorRole: "APPROVER",
        content: "อนุมัติบรรจุในแผนจัดซื้อครุภัณฑ์ประจำปีงบประมาณ 2570 เนื่องจากสอดคล้องตามเกณฑ์ราคากลางกระทรวงดิจิทัลฯ",
        action: "APPROVE",
        createdAt: "2026-08-22T16:00:00Z",
      },
    ],
  },
  {
    id: "req-003",
    code: "REQ-2570-003",
    title: "เครื่องคอมพิวเตอร์แม่ข่าย GPU สำหรับงาน Deep Learning และ Large Language Models",
    faculty: "คณะวิทยาศาสตร์",
    department: "สาขาวิชาเคมี",
    requesterId: "emp-005",
    requesterName: "ผศ.ดร.วิภาดา สมบูรณ์",
    requesterEmail: "vipada.s@kku.ac.th",
    status: "SUBMITTED",
    fiscalYear: 2570,
    category: "ครุภัณฑ์คอมพิวเตอร์",
    totalBudgetBaht: 1400000,
    quantity: 2,
    unit: "เครื่อง",
    unitPriceBaht: 700000,
    standardMatched: false,
    standardName: "เครื่องคอมพิวเตอร์แม่ข่ายสมรรถนะสูงเฉพาะทาง (GPU Server)",
    alertLevel: "CUSTOM_NON_STANDARD",
    createdAt: "2026-08-18T11:20:00Z",
    updatedAt: "2026-08-24T10:15:00Z",
    attachments: [
      {
        id: "att-003-1",
        type: "QUOTATIONS_3_PDF",
        fileName: "3_quotes_gpu_server_ai.pdf",
        fileSize: 5600000,
        contentType: "application/pdf",
        storageKey: "quotations/req-003-3quotes.pdf",
        uploadedAt: "2026-08-18T11:45:00Z",
      },
      {
        id: "att-003-2",
        type: "PHOTO_EQUIPMENT",
        fileName: "server_rack_room_cp.jpg",
        fileSize: 3100000,
        contentType: "image/jpeg",
        storageKey: "photos/req-003-rack.jpg",
        uploadedAt: "2026-08-18T11:50:00Z",
      },
    ],
    reviewComments: [
      {
        id: "comm-003-1",
        authorId: "emp-002",
        authorName: "นายประเสริฐ รักงาน",
        authorRole: "DEPT_VERIFIER",
        content: "ผ่านการตรวจสอบเอกสารความจำเป็นเชิงเทคนิคและใบเสนอราคา 3 ราย มีความพร้อมเรื่องห้อง Server Room และระบบไฟฟ้าสำรอง UPS",
        action: "APPROVE",
        createdAt: "2026-08-24T10:15:00Z",
      },
    ],
  },
  {
    id: "req-004",
    code: "REQ-2570-004",
    title: "เครื่องคอมพิวเตอร์ สำหรับห้องสืบค้นและบริการสารสนเทศนิสิต",
    faculty: "สำนักหอสมุด",
    department: "ฝ่ายบริการสารสนเทศ",
    requesterId: "emp-006",
    requesterName: "นางรัชนี บุญเรือง",
    requesterEmail: "ratchanee.b@kku.ac.th",
    status: "APPROVED",
    fiscalYear: 2570,
    category: "ครุภัณฑ์คอมพิวเตอร์",
    totalBudgetBaht: 510000,
    quantity: 30,
    unit: "เครื่อง",
    unitPriceBaht: 17000,
    standardMatched: true,
    standardName: "เครื่องคอมพิวเตอร์ สำหรับงานสำนักงาน *(จอแสดงภาพขนาดไม่น้อยกว่า 19.5 นิ้ว)",
    alertLevel: "GREEN_MATCH",
    createdAt: "2026-08-15T08:30:00Z",
    updatedAt: "2026-08-19T13:40:00Z",
    attachments: [
      {
        id: "att-004-1",
        type: "SPEC_PDF",
        fileName: "library_pc_standard_spec.pdf",
        fileSize: 980000,
        contentType: "application/pdf",
        storageKey: "specs/req-004-spec.pdf",
        uploadedAt: "2026-08-15T08:50:00Z",
      },
    ],
  },
  {
    id: "req-005",
    code: "REQ-2570-005",
    title: "ระบบจัดเก็บข้อมูลบนเครือข่ายความเร็วสูง (Enterprise Storage NAS 120TB)",
    faculty: "ศูนย์คอมพิวเตอร์",
    department: "ฝ่ายโครงสร้างพื้นฐานระบบเครือข่าย",
    requesterId: "emp-007",
    requesterName: "นายพิชัย ยอดดำเนิน",
    requesterEmail: "pichai.y@kku.ac.th",
    status: "DEPT_REVIEW",
    fiscalYear: 2570,
    category: "ครุภัณฑ์คอมพิวเตอร์",
    totalBudgetBaht: 450000,
    quantity: 1,
    unit: "ระบบ",
    unitPriceBaht: 450000,
    standardMatched: false,
    standardName: "อุปกรณ์จัดเก็บข้อมูลเครือข่ายระดับองค์กร (Enterprise NAS)",
    alertLevel: "CUSTOM_NON_STANDARD",
    createdAt: "2026-08-22T14:10:00Z",
    updatedAt: "2026-08-23T09:00:00Z",
  },
  {
    id: "req-006",
    code: "REQ-2570-006",
    title: "เครื่องคอมพิวเตอร์พกพา สำหรับงานออกแบบสถาปัตยกรรมและแบบจำลองสารสนเทศอาคาร (BIM)",
    faculty: "คณะสถาปัตยกรรมศาสตร์",
    department: "สาขาวิชาการออกแบบอุตสาหกรรม",
    requesterId: "emp-008",
    requesterName: "ผศ.ดร.กานต์พิชชา ภักดี",
    requesterEmail: "karnpitcha.p@kku.ac.th",
    status: "REVISED",
    fiscalYear: 2570,
    category: "ครุภัณฑ์คอมพิวเตอร์",
    totalBudgetBaht: 320000,
    quantity: 8,
    unit: "เครื่อง",
    unitPriceBaht: 40000,
    standardMatched: true,
    standardName: "เครื่องคอมพิวเตอร์พกพา (Notebook) สำหรับงานประมวลผล",
    alertLevel: "AMBER_ALERT",
    createdAt: "2026-08-12T10:00:00Z",
    updatedAt: "2026-08-27T15:20:00Z",
    reviewComments: [
      {
        id: "comm-006-1",
        authorId: "emp-002",
        authorName: "นายประเสริฐ รักงาน",
        authorRole: "DEPT_VERIFIER",
        content: "กรุณาแนบใบเสนอราคาให้ครบ 3 เจ้า และตัดข้อความที่ระบุยี่ห้อการ์ดจอเฉพาะเจาะจงออก ให้ใช้คำว่า 'หรือเทียบเท่า'",
        action: "REQUEST_CHANGE",
        createdAt: "2026-08-27T15:20:00Z",
      },
    ],
  },
  {
    id: "req-007",
    code: "REQ-2570-007",
    title: "เครื่องคอมพิวเตอร์ สำหรับห้องปฏิบัติการหุ่นยนต์และระบบสมองกลฝังตัว",
    faculty: "คณะวิศวกรรมศาสตร์",
    department: "สาขาวิชาวิศวกรรมคอมพิวเตอร์",
    requesterId: "emp-009",
    requesterName: "รศ.ดร.ธนากร สินธุสาย",
    requesterEmail: "thanakorn.s@kku.ac.th",
    status: "SUBMITTED",
    fiscalYear: 2570,
    category: "ครุภัณฑ์คอมพิวเตอร์",
    totalBudgetBaht: 660000,
    quantity: 20,
    unit: "เครื่อง",
    unitPriceBaht: 33000,
    standardMatched: true,
    standardName: "เครื่องคอมพิวเตอร์ สำหรับงานประมวลผล แบบที่ 2 *(จอแสดงภาพขนาดไม่น้อยกว่า 23 นิ้ว พร้อมการ์ดจอแยก)",
    alertLevel: "GREEN_MATCH",
    createdAt: "2026-08-16T13:15:00Z",
    updatedAt: "2026-08-21T11:00:00Z",
  },
  {
    id: "req-008",
    code: "REQ-2570-008",
    title: "อุปกรณ์กระจายสัญญาณเครือข่ายไร้สายความเร็วสูงมาตรฐาน Wi-Fi 7",
    faculty: "ศูนย์คอมพิวเตอร์",
    department: "ฝ่ายโครงสร้างพื้นฐานระบบเครือข่าย",
    requesterId: "emp-007",
    requesterName: "นายพิชัย ยอดดำเนิน",
    requesterEmail: "pichai.y@kku.ac.th",
    status: "APPROVED",
    fiscalYear: 2570,
    category: "ครุภัณฑ์คอมพิวเตอร์",
    totalBudgetBaht: 720000,
    quantity: 24,
    unit: "เครื่อง",
    unitPriceBaht: 30000,
    standardMatched: true,
    standardName: "อุปกรณ์กระจายสัญญาณไร้สาย (Access Point) ระดับองค์กร",
    alertLevel: "GREEN_MATCH",
    createdAt: "2026-08-10T09:00:00Z",
    updatedAt: "2026-08-14T17:00:00Z",
  },
  {
    id: "req-009",
    code: "REQ-2570-009",
    title: "เครื่องคอมพิวเตอร์ All-in-One สำหรับเคาน์เตอร์เวชระเบียนและบริการผู้ป่วยนอก",
    faculty: "คณะแพทยศาสตร์",
    department: "โรงพยาบาลศรีนครินทร์",
    requesterId: "emp-010",
    requesterName: "นางสาวศิริพร บุญตา",
    requesterEmail: "siriporn.b@kku.ac.th",
    status: "APPROVED",
    fiscalYear: 2570,
    category: "ครุภัณฑ์คอมพิวเตอร์",
    totalBudgetBaht: 425000,
    quantity: 25,
    unit: "เครื่อง",
    unitPriceBaht: 17000,
    standardMatched: true,
    standardName: "เครื่องคอมพิวเตอร์ สำหรับงานสำนักงาน *(จอแสดงภาพขนาดไม่น้อยกว่า 19.5 นิ้ว)",
    alertLevel: "GREEN_MATCH",
    createdAt: "2026-08-08T08:15:00Z",
    updatedAt: "2026-08-11T14:30:00Z",
  },
  {
    id: "req-010",
    code: "REQ-2570-010",
    title: "เครื่องคอมพิวเตอร์แม่ข่ายประมวลผลฐานข้อมูล (Database Server)",
    faculty: "คณะวิทยาศาสตร์",
    department: "สาขาวิชาเคมี",
    requesterId: "emp-005",
    requesterName: "ผศ.ดร.วิภาดา สมบูรณ์",
    requesterEmail: "vipada.s@kku.ac.th",
    status: "DRAFT",
    fiscalYear: 2570,
    category: "ครุภัณฑ์คอมพิวเตอร์",
    totalBudgetBaht: 380000,
    quantity: 1,
    unit: "เครื่อง",
    unitPriceBaht: 380000,
    standardMatched: true,
    standardName: "เครื่องคอมพิวเตอร์แม่ข่าย แบบที่ 1",
    alertLevel: "GREEN_MATCH",
    createdAt: "2026-08-28T16:00:00Z",
    updatedAt: "2026-08-28T16:00:00Z",
  },

  // ==========================================
  // หมวดที่ 2: ครุภัณฑ์วิทยาศาสตร์และการวิจัย (8 รายการ)
  // ==========================================
  {
    id: "req-011",
    code: "REQ-2570-011",
    title: "เครื่องปั่นเหวี่ยงตกตะกอนควบคุมอุณหภูมิความเร็วรอบสูง (Refrigerated High-Speed Centrifuge)",
    faculty: "คณะวิทยาศาสตร์",
    department: "สาขาวิชาชีวเคมี",
    requesterId: "emp-011",
    requesterName: "รศ.ดร.พิมพาภรณ์ สุวรรณฉัตร",
    requesterEmail: "pimpaporn.s@kku.ac.th",
    status: "DEPT_REVIEW",
    fiscalYear: 2570,
    category: "ครุภัณฑ์วิทยาศาสตร์",
    totalBudgetBaht: 700000,
    quantity: 2,
    unit: "เครื่อง",
    unitPriceBaht: 350000,
    standardMatched: true,
    standardName: "เครื่องปั่นเหวี่ยงตกตะกอนควบคุมอุณหภูมิ (Refrigerated Centrifuge)",
    alertLevel: "GREEN_MATCH",
    createdAt: "2026-08-21T10:30:00Z",
    updatedAt: "2026-08-23T11:00:00Z",
    attachments: [
      {
        id: "att-011-1",
        type: "PHOTO_EQUIPMENT",
        fileName: "biochem_lab_space.jpg",
        fileSize: 1800000,
        contentType: "image/jpeg",
        storageKey: "photos/req-011-lab.jpg",
        uploadedAt: "2026-08-21T10:45:00Z",
      },
    ],
  },
  {
    id: "req-012",
    code: "REQ-2570-012",
    title: "เครื่องวัดการดูดกลืนแสงแบบยูวี-วิสิเบิล (UV-Vis Double Beam Spectrophotometer)",
    faculty: "คณะวิทยาศาสตร์",
    department: "สาขาวิชาฟิสิกส์",
    requesterId: "emp-012",
    requesterName: "รศ.ดร.อนันต์ สิทธิชัย",
    requesterEmail: "anan.s@kku.ac.th",
    status: "SUBMITTED",
    fiscalYear: 2570,
    category: "ครุภัณฑ์วิทยาศาสตร์",
    totalBudgetBaht: 280000,
    quantity: 1,
    unit: "เครื่อง",
    unitPriceBaht: 280000,
    standardMatched: true,
    standardName: "เครื่องวัดการดูดกลืนแสงแบบยูวี-วิสิเบิล (UV-Vis Spectrophotometer)",
    alertLevel: "GREEN_MATCH",
    createdAt: "2026-08-19T09:10:00Z",
    updatedAt: "2026-08-22T14:20:00Z",
  },
  {
    id: "req-013",
    code: "REQ-2570-013",
    title: "กล้องจุลทรรศน์อิเล็กตรอนแบบส่องกราดสมรรถนะสูง (Field Emission Scanning Electron Microscope - FE-SEM)",
    faculty: "คณะวิทยาศาสตร์",
    department: "ศูนย์เครื่องมือวิจัยขั้นสูง มข.",
    requesterId: "emp-013",
    requesterName: "ศ.ดร.เกียรติศักดิ์ พรหมดี",
    requesterEmail: "kiattisak.p@kku.ac.th",
    status: "SUBMITTED",
    fiscalYear: 2570,
    category: "ครุภัณฑ์วิทยาศาสตร์",
    totalBudgetBaht: 18500000,
    quantity: 1,
    unit: "ชุด",
    unitPriceBaht: 18500000,
    standardMatched: false,
    standardName: "กล้องจุลทรรศน์อิเล็กตรอนแบบส่องกราด (FE-SEM)",
    alertLevel: "CUSTOM_NON_STANDARD",
    createdAt: "2026-08-05T14:00:00Z",
    updatedAt: "2026-08-25T16:30:00Z",
    attachments: [
      {
        id: "att-013-1",
        type: "FEASIBILITY_PDF",
        fileName: "feasibility_study_fesem_center.pdf",
        fileSize: 8900000,
        contentType: "application/pdf",
        storageKey: "feasibility/req-013-fesem.pdf",
        uploadedAt: "2026-08-05T14:15:00Z",
      },
      {
        id: "att-013-2",
        type: "QUOTATIONS_3_PDF",
        fileName: "3_quotes_fesem_system.pdf",
        fileSize: 6400000,
        contentType: "application/pdf",
        storageKey: "quotations/req-013-quotes.pdf",
        uploadedAt: "2026-08-05T14:20:00Z",
      },
    ],
    reviewComments: [
      {
        id: "comm-013-1",
        authorId: "emp-004",
        authorName: "นางสาวกรกนก เพชรแท้",
        authorRole: "ADMIN",
        content: "โครงการมีวงเงินเกิน 10 ล้านบาท ตรวจสอบเอกสารรายงานการศึกษาความคุ้มค่า (Feasibility Study) และแผนซ่อมบำรุงแล้ว ครบถ้วนตามระเบียบ",
        action: "COMMENT",
        createdAt: "2026-08-25T16:30:00Z",
      },
    ],
  },
  {
    id: "req-014",
    code: "REQ-2570-014",
    title: "เครื่องโครมาโทกราฟีของเหลวสมรรถนะสูง (High-Performance Liquid Chromatography - HPLC)",
    faculty: "คณะเภสัชศาสตร์",
    department: "สาขาวิชาเภสัชเคมี",
    requesterId: "emp-014",
    requesterName: "รศ.ดร.ภก.อรรถพล โชคอำนวย",
    requesterEmail: "attapol.c@kku.ac.th",
    status: "APPROVED",
    fiscalYear: 2570,
    category: "ครุภัณฑ์วิทยาศาสตร์",
    totalBudgetBaht: 1850000,
    quantity: 1,
    unit: "เครื่อง",
    unitPriceBaht: 1850000,
    standardMatched: false,
    standardName: "เครื่องวิเคราะห์สารด้วยเทคนิคโครมาโทกราฟีของเหลว",
    alertLevel: "CUSTOM_NON_STANDARD",
    createdAt: "2026-08-11T09:40:00Z",
    updatedAt: "2026-08-16T15:00:00Z",
  },
  {
    id: "req-015",
    code: "REQ-2570-015",
    title: "ตู้เพาะเลี้ยงเซลล์ควบคุมก๊าซคาร์บอนไดออกไซด์ (CO2 Incubator with Tri-gas Control)",
    faculty: "คณะแพทยศาสตร์",
    department: "หน่วยวิจัยชีววิทยาโมเลกุลทางการแพทย์",
    requesterId: "emp-015",
    requesterName: "ศ.พญ.พรรณพิศ สุริโย",
    requesterEmail: "panpis.s@kku.ac.th",
    status: "DEPT_REVIEW",
    fiscalYear: 2570,
    category: "ครุภัณฑ์วิทยาศาสตร์",
    totalBudgetBaht: 780000,
    quantity: 2,
    unit: "ตู้",
    unitPriceBaht: 390000,
    standardMatched: true,
    standardName: "ตู้เพาะเลี้ยงเซลล์ควบคุมก๊าซคาร์บอนไดออกไซด์",
    alertLevel: "AMBER_ALERT",
    createdAt: "2026-08-23T11:00:00Z",
    updatedAt: "2026-08-24T08:30:00Z",
  },
  {
    id: "req-016",
    code: "REQ-2570-016",
    title: "เครื่องเพิ่มปริมาณสารพันธุกรรมแบบ Real-time PCR (Quantitative Real-time PCR System)",
    faculty: "คณะสัตวแพทยศาสตร์",
    department: "สาขาวิชาพยาธิชีววิทยา",
    requesterId: "emp-016",
    requesterName: "ผศ.น.สพ.ดร.วรวิทย์ สุขสม",
    requesterEmail: "worawit.s@kku.ac.th",
    status: "AI_ANALYZED",
    fiscalYear: 2570,
    category: "ครุภัณฑ์วิทยาศาสตร์",
    totalBudgetBaht: 1200000,
    quantity: 1,
    unit: "เครื่อง",
    unitPriceBaht: 1200000,
    standardMatched: false,
    standardName: "เครื่อง Real-time PCR สำหรับงานวิจัยทางอณูชีววิทยา",
    alertLevel: "CUSTOM_NON_STANDARD",
    createdAt: "2026-08-26T15:20:00Z",
    updatedAt: "2026-08-26T15:25:00Z",
  },
  {
    id: "req-017",
    code: "REQ-2570-017",
    title: "ตู้ดูดควันและไอสารเคมีพร้อมระบบกรองและบำบัดไอพิษ (Ducted Fume Hood Class A)",
    faculty: "คณะวิทยาศาสตร์",
    department: "สาขาวิชาฟิสิกส์",
    requesterId: "emp-012",
    requesterName: "รศ.ดร.อนันต์ สิทธิชัย",
    requesterEmail: "anan.s@kku.ac.th",
    status: "APPROVED",
    fiscalYear: 2570,
    category: "ครุภัณฑ์วิทยาศาสตร์",
    totalBudgetBaht: 900000,
    quantity: 3,
    unit: "ตู้",
    unitPriceBaht: 300000,
    standardMatched: true,
    standardName: "ตู้ดูดควันไอสารเคมี (Fume Hood)",
    alertLevel: "GREEN_MATCH",
    createdAt: "2026-08-07T10:00:00Z",
    updatedAt: "2026-08-12T11:45:00Z",
  },
  {
    id: "req-018",
    code: "REQ-2570-018",
    title: "เครื่องวัดขนาดอนุภาคและศักย์ซีต้า (Zeta Potential and Particle Size Analyzer)",
    faculty: "คณะวิทยาศาสตร์",
    department: "สาขาวิชาฟิสิกส์",
    requesterId: "emp-017",
    requesterName: "รศ.ดร.อานนท์ ธรรมรัตน์",
    requesterEmail: "arnon.t@kku.ac.th",
    status: "DRAFT",
    fiscalYear: 2570,
    category: "ครุภัณฑ์วิทยาศาสตร์",
    totalBudgetBaht: 2400000,
    quantity: 1,
    unit: "เครื่อง",
    unitPriceBaht: 2400000,
    standardMatched: false,
    standardName: "เครื่องวิเคราะห์ขนาดอนุภาคระดับนาโนเมตร",
    alertLevel: "CUSTOM_NON_STANDARD",
    createdAt: "2026-08-29T10:15:00Z",
    updatedAt: "2026-08-29T10:15:00Z",
  },

  // ==========================================
  // หมวดที่ 3: ครุภัณฑ์การศึกษาและห้องปฏิบัติการ (6 รายการ)
  // ==========================================
  {
    id: "req-019",
    code: "REQ-2570-019",
    title: "จอสัมผัสอัจฉริยะเพื่อการเรียนการสอน (Interactive Smart Display 75 นิ้ว)",
    faculty: "คณะมนุษยศาสตร์และสังคมศาสตร์",
    department: "สาขาวิชาภาษาอังกฤษ",
    requesterId: "emp-018",
    requesterName: "ผศ.ดร.วรรณภา จินดา",
    requesterEmail: "wannapa.j@kku.ac.th",
    status: "APPROVED",
    fiscalYear: 2570,
    category: "ครุภัณฑ์การศึกษาและห้องปฏิบัติการ",
    totalBudgetBaht: 570000,
    quantity: 6,
    unit: "เครื่อง",
    unitPriceBaht: 95000,
    standardMatched: true,
    standardName: "จอสัมผัสอัจฉริยะเพื่อการเรียนการสอน (Interactive Smart Display 75 นิ้ว)",
    alertLevel: "GREEN_MATCH",
    createdAt: "2026-08-14T08:45:00Z",
    updatedAt: "2026-08-18T16:10:00Z",
  },
  {
    id: "req-020",
    code: "REQ-2570-020",
    title: "ชุดระบบจำลองการฝึกทักษะการพยาบาลเสมือนจริงขั้นสูง (High-Fidelity Nursing Simulation System)",
    faculty: "คณะพยาบาลศาสตร์",
    department: "กลุ่มวิชาการพยาบาลผู้ใหญ่และผู้สูงอายุ",
    requesterId: "emp-019",
    requesterName: "รศ.ดร.อรัญญา ว่องวิทย์",
    requesterEmail: "aranya.w@kku.ac.th",
    status: "SUBMITTED",
    fiscalYear: 2570,
    category: "ครุภัณฑ์การศึกษาและห้องปฏิบัติการ",
    totalBudgetBaht: 12500000,
    quantity: 1,
    unit: "ระบบ",
    unitPriceBaht: 12500000,
    standardMatched: false,
    standardName: "ระบบหุ่นจำลองฝึกปฏิบัติการพยาบาลเสมือนจริง",
    alertLevel: "CUSTOM_NON_STANDARD",
    createdAt: "2026-08-04T13:00:00Z",
    updatedAt: "2026-08-20T14:30:00Z",
    attachments: [
      {
        id: "att-020-1",
        type: "FEASIBILITY_PDF",
        fileName: "nursing_simulation_feasibility.pdf",
        fileSize: 7200000,
        contentType: "application/pdf",
        storageKey: "feasibility/req-020-sim.pdf",
        uploadedAt: "2026-08-04T13:15:00Z",
      },
    ],
  },
  {
    id: "req-021",
    code: "REQ-2570-021",
    title: "ชุดเครื่องเสียงและระบบโสตทัศนูปกรณ์สำหรับห้องบรรยายขนาดใหญ่ 300 ที่นั่ง",
    faculty: "คณะบริหารธุรกิจและการบัญชี",
    department: "ศูนย์นวัตกรรมธุรกิจ",
    requesterId: "emp-020",
    requesterName: "ผศ.ดร.อนุสรณ์ ไชยเดช",
    requesterEmail: "anusorn.c@kku.ac.th",
    status: "DEPT_REVIEW",
    fiscalYear: 2570,
    category: "ครุภัณฑ์การศึกษาและห้องปฏิบัติการ",
    totalBudgetBaht: 650000,
    quantity: 1,
    unit: "ชุด",
    unitPriceBaht: 650000,
    standardMatched: true,
    standardName: "ระบบเครื่องเสียงและโสตทัศนูปกรณ์ห้องประชุม/บรรยาย",
    alertLevel: "AMBER_ALERT",
    createdAt: "2026-08-22T09:30:00Z",
    updatedAt: "2026-08-25T11:20:00Z",
  },
  {
    id: "req-022",
    code: "REQ-2570-022",
    title: "ชุดฝึกทดลองระบบอัตโนมัติและแขนกลหุ่นยนต์อุตสาหกรรม (Industrial Robotics Training Kit)",
    faculty: "คณะวิศวกรรมศาสตร์",
    department: "สาขาวิชาวิศวกรรมเครื่องกล",
    requesterId: "emp-021",
    requesterName: "รศ.ดร.พิศาล เจริญพานิช",
    requesterEmail: "pisan.c@kku.ac.th",
    status: "AI_ANALYZED",
    fiscalYear: 2570,
    category: "ครุภัณฑ์การศึกษาและห้องปฏิบัติการ",
    totalBudgetBaht: 1800000,
    quantity: 2,
    unit: "ชุด",
    unitPriceBaht: 900000,
    standardMatched: false,
    standardName: "ชุดปฏิบัติการแขนกลหุ่นยนต์อุตสาหกรรม",
    alertLevel: "CUSTOM_NON_STANDARD",
    createdAt: "2026-08-27T10:00:00Z",
    updatedAt: "2026-08-27T10:05:00Z",
  },
  {
    id: "req-023",
    code: "REQ-2570-023",
    title: "เครื่องจำลองการรักษาทางทันตกรรมเสมือนจริง (Virtual Dental Simulator with Haptic Feedback)",
    faculty: "คณะทันตแพทยศาสตร์",
    department: "ภาควิชาทันตกรรมบูรณะ",
    requesterId: "emp-022",
    requesterName: "ศ.ทพ.ดร.สกล ศรีมณฑา",
    requesterEmail: "sakol.s@kku.ac.th",
    status: "SUBMITTED",
    fiscalYear: 2570,
    category: "ครุภัณฑ์การศึกษาและห้องปฏิบัติการ",
    totalBudgetBaht: 4800000,
    quantity: 2,
    unit: "เครื่อง",
    unitPriceBaht: 2400000,
    standardMatched: false,
    standardName: "เครื่องจำลองหัตถการทางทันตกรรมเสมือนจริง",
    alertLevel: "CUSTOM_NON_STANDARD",
    createdAt: "2026-08-16T14:40:00Z",
    updatedAt: "2026-08-23T10:00:00Z",
  },
  {
    id: "req-024",
    code: "REQ-2570-024",
    title: "อากาศยานไร้คนขับ (โดรน) เพื่อการสำรวจและทำแผนที่ภาพถ่ายความละเอียดสูงด้านธรณีวิทยา",
    faculty: "คณะเทคโนโลยี",
    department: "สาขาวิชาเทคโนโลยีธรณี",
    requesterId: "emp-023",
    requesterName: "ผศ.ดร.ชูชาติ มั่งมี",
    requesterEmail: "choochart.m@kku.ac.th",
    status: "REVISED",
    fiscalYear: 2570,
    category: "ครุภัณฑ์การศึกษาและห้องปฏิบัติการ",
    totalBudgetBaht: 450000,
    quantity: 1,
    unit: "ชุด",
    unitPriceBaht: 450000,
    standardMatched: true,
    standardName: "อากาศยานไร้คนขับสำหรับการสำรวจและทำแผนที่",
    alertLevel: "AMBER_ALERT",
    createdAt: "2026-08-10T11:15:00Z",
    updatedAt: "2026-08-26T13:40:00Z",
    reviewComments: [
      {
        id: "comm-024-1",
        authorId: "emp-002",
        authorName: "นายประเสริฐ รักงาน",
        authorRole: "DEPT_VERIFIER",
        content: "กรุณาแนบเอกสารใบอนุญาตหรือข้อกำหนดด้านการบินอากาศยานไร้คนขับตามกฎหมายของ กพท. (CAAT) เพิ่มเติมในช่องหมายเหตุ",
        action: "REQUEST_CHANGE",
        createdAt: "2026-08-26T13:40:00Z",
      },
    ],
  },

  // ==========================================
  // หมวดที่ 4: ครุภัณฑ์การแพทย์และสาธารณสุข (5 รายการ)
  // ==========================================
  {
    id: "req-025",
    code: "REQ-2570-025",
    title: "เครื่องตรวจอวัยวะภายในด้วยคลื่นเสียงความถี่สูงระบบดอปเปลอร์สี (Color Doppler Ultrasound)",
    faculty: "คณะแพทยศาสตร์",
    department: "โรงพยาบาลศรีนครินทร์",
    requesterId: "emp-024",
    requesterName: "ศ.นพ.ธีระวัฒน์ จิตเจริญ",
    requesterEmail: "theerawat.j@kku.ac.th",
    status: "SUBMITTED",
    fiscalYear: 2570,
    category: "ครุภัณฑ์การแพทย์",
    totalBudgetBaht: 3800000,
    quantity: 1,
    unit: "เครื่อง",
    unitPriceBaht: 3800000,
    standardMatched: true,
    standardName: "เครื่องตรวจอวัยวะภายในด้วยคลื่นเสียงความถี่สูง ชนิดดอปเปลอร์สี",
    alertLevel: "AMBER_ALERT",
    createdAt: "2026-08-12T09:00:00Z",
    updatedAt: "2026-08-24T15:00:00Z",
  },
  {
    id: "req-026",
    code: "REQ-2570-026",
    title: "เครื่องตรวจติดตามการทำงานของหัวใจและสัญญาณชีพข้างเตียงผู้ป่วย (Bedside Patient Monitor 6 Parameters)",
    faculty: "คณะแพทยศาสตร์",
    department: "หอผู้ป่วยวิกฤตอายุรกรรม (ICU)",
    requesterId: "emp-024",
    requesterName: "ศ.นพ.ธีระวัฒน์ จิตเจริญ",
    requesterEmail: "theerawat.j@kku.ac.th",
    status: "APPROVED",
    fiscalYear: 2570,
    category: "ครุภัณฑ์การแพทย์",
    totalBudgetBaht: 1200000,
    quantity: 4,
    unit: "เครื่อง",
    unitPriceBaht: 300000,
    standardMatched: true,
    standardName: "เครื่องติดตามการทำงานของหัวใจและสัญญาณชีพผู้ป่วยข้างเตียง",
    alertLevel: "GREEN_MATCH",
    createdAt: "2026-08-06T14:20:00Z",
    updatedAt: "2026-08-15T10:30:00Z",
  },
  {
    id: "req-027",
    code: "REQ-2570-027",
    title: "เครื่องตรวจคลื่นไฟฟ้าหัวใจ 12 ลีด พร้อมระบบบันทึกและแปลผลอัตโนมัติ (12-Lead ECG Machine)",
    faculty: "คณะแพทยศาสตร์",
    department: "ศูนย์การแพทย์ปฐมภูมิ",
    requesterId: "emp-025",
    requesterName: "พญ.กรรณิการ์ จันทร์เพ็ญ",
    requesterEmail: "kannika.j@kku.ac.th",
    status: "APPROVED",
    fiscalYear: 2570,
    category: "ครุภัณฑ์การแพทย์",
    totalBudgetBaht: 360000,
    quantity: 2,
    unit: "เครื่อง",
    unitPriceBaht: 180000,
    standardMatched: true,
    standardName: "เครื่องตรวจคลื่นไฟฟ้าหัวใจ 12 ลีด",
    alertLevel: "GREEN_MATCH",
    createdAt: "2026-08-09T11:00:00Z",
    updatedAt: "2026-08-14T09:15:00Z",
  },
  {
    id: "req-028",
    code: "REQ-2570-028",
    title: "เครื่องกระตุกหัวใจด้วยไฟฟ้าแบบอัตโนมัติ (Automated External Defibrillator - AED) สำหรับอาคารเรียนรวม",
    faculty: "กองพัฒนานักศึกษา",
    department: "งานบริการสุขภาพและอนามัย",
    requesterId: "emp-026",
    requesterName: "นายณัฐวุฒิ สิทธิชัย",
    requesterEmail: "nattawut.s@kku.ac.th",
    status: "APPROVED",
    fiscalYear: 2570,
    category: "ครุภัณฑ์การแพทย์",
    totalBudgetBaht: 400000,
    quantity: 5,
    unit: "เครื่อง",
    unitPriceBaht: 80000,
    standardMatched: true,
    standardName: "เครื่องฟื้นคืนคลื่นหัวใจด้วยไฟฟ้าแบบอัตโนมัติ (AED)",
    alertLevel: "GREEN_MATCH",
    createdAt: "2026-08-03T08:30:00Z",
    updatedAt: "2026-08-10T16:00:00Z",
  },
  {
    id: "req-029",
    code: "REQ-2570-029",
    title: "ยูนิตทำฟันและเก้าอี้ทันตกรรมพร้อมระบบดูดน้ำลายและโคมไฟ LED ผ่าตัด",
    faculty: "คณะทันตแพทยศาสตร์",
    department: "คลินิกทันตกรรมบริการ",
    requesterId: "emp-022",
    requesterName: "ศ.ทพ.ดร.สกล ศรีมณฑา",
    requesterEmail: "sakol.s@kku.ac.th",
    status: "DEPT_REVIEW",
    fiscalYear: 2570,
    category: "ครุภัณฑ์การแพทย์",
    totalBudgetBaht: 1650000,
    quantity: 3,
    unit: "ชุด",
    unitPriceBaht: 550000,
    standardMatched: true,
    standardName: "ยูนิตทำฟัน (Dental Unit)",
    alertLevel: "AMBER_ALERT",
    createdAt: "2026-08-20T10:00:00Z",
    updatedAt: "2026-08-25T14:15:00Z",
  },

  // ==========================================
  // หมวดที่ 5: ครุภัณฑ์สำนักงาน (4 รายการ)
  // ==========================================
  {
    id: "req-030",
    code: "REQ-2570-030",
    title: "เครื่องถ่ายเอกสารระบบดิจิทัลมัลติฟังก์ชัน สี/ขาวดำ ความเร็วไม่น้อยกว่า 35 แผ่นต่อนาที",
    faculty: "คณะแพทยศาสตร์",
    department: "สำนักงานคณบดี",
    requesterId: "emp-027",
    requesterName: "นางจันทิมา วรวิทย์",
    requesterEmail: "jantima.w@kku.ac.th",
    status: "APPROVED",
    fiscalYear: 2570,
    category: "ครุภัณฑ์สำนักงาน",
    totalBudgetBaht: 220000,
    quantity: 2,
    unit: "เครื่อง",
    unitPriceBaht: 110000,
    standardMatched: true,
    standardName: "เครื่องถ่ายเอกสารระบบดิจิทัล (ขาวดำ-สี)",
    alertLevel: "GREEN_MATCH",
    createdAt: "2026-08-11T13:20:00Z",
    updatedAt: "2026-08-15T11:00:00Z",
  },
  {
    id: "req-031",
    code: "REQ-2570-031",
    title: "เครื่องพิมพ์มัลติฟังก์ชันระบบเลเซอร์เครือข่ายความเร็วสูง",
    faculty: "คณะมนุษยศาสตร์และสังคมศาสตร์",
    department: "งานบริหารงานทั่วไป",
    requesterId: "emp-028",
    requesterName: "นายสมเกียรติ สว่างวงศ์",
    requesterEmail: "somkiat.s@kku.ac.th",
    status: "AI_ANALYZED",
    fiscalYear: 2570,
    category: "ครุภัณฑ์สำนักงาน",
    totalBudgetBaht: 76000,
    quantity: 4,
    unit: "เครื่อง",
    unitPriceBaht: 19000,
    standardMatched: true,
    standardName: "เครื่องพิมพ์เลเซอร์มัลติฟังก์ชัน",
    alertLevel: "GREEN_MATCH",
    createdAt: "2026-08-27T14:10:00Z",
    updatedAt: "2026-08-27T14:15:00Z",
  },
  {
    id: "req-032",
    code: "REQ-2570-032",
    title: "เครื่องทำลายเอกสารลับความละเอียดสูงระดับมาตรฐานความปลอดภัย DIN P-5",
    faculty: "กองบริหารงานกลาง",
    department: "งานสารบรรณและนิติการ",
    requesterId: "emp-029",
    requesterName: "นางนฤมล พรหมมินทร์",
    requesterEmail: "narumon.p@kku.ac.th",
    status: "APPROVED",
    fiscalYear: 2570,
    category: "ครุภัณฑ์สำนักงาน",
    totalBudgetBaht: 90000,
    quantity: 3,
    unit: "เครื่อง",
    unitPriceBaht: 30000,
    standardMatched: true,
    standardName: "เครื่องทำลายเอกสารแบบตัดละเอียด",
    alertLevel: "GREEN_MATCH",
    createdAt: "2026-08-05T09:00:00Z",
    updatedAt: "2026-08-08T15:30:00Z",
  },
  {
    id: "req-033",
    code: "REQ-2570-033",
    title: "ระบบตู้เหล็กเก็บเอกสารสำคัญแบบรางเลื่อนประหยัดพื้นที่ (Mobile Compactor Cabinet System)",
    faculty: "กองคลังและพัสดุ",
    department: "งานบริหารพัสดุและทรัพย์สิน",
    requesterId: "emp-004",
    requesterName: "นางสาวกรกนก เพชรแท้",
    requesterEmail: "admin.procure@kku.ac.th",
    status: "SUBMITTED",
    fiscalYear: 2570,
    category: "ครุภัณฑ์สำนักงาน",
    totalBudgetBaht: 480000,
    quantity: 1,
    unit: "ระบบ",
    unitPriceBaht: 480000,
    standardMatched: false,
    standardName: "ระบบตู้จัดเก็บเอกสารรางเลื่อนระบบพวงมาลัยกล",
    alertLevel: "CUSTOM_NON_STANDARD",
    createdAt: "2026-08-17T15:00:00Z",
    updatedAt: "2026-08-22T13:40:00Z",
  },

  // ==========================================
  // หมวดที่ 6: ครุภัณฑ์การเกษตรและสิ่งแวดล้อม (3 รายการ)
  // ==========================================
  {
    id: "req-034",
    code: "REQ-2570-034",
    title: "โรงเรือนเพาะปลูกอัจฉริยะควบคุมสภาพแวดล้อมระบบ IoT (Smart Precision Greenhouse System)",
    faculty: "คณะเกษตรศาสตร์",
    department: "สาขาวิชาพืชศาสตร์และปฐพีศาสตร์",
    requesterId: "emp-030",
    requesterName: "รศ.ดร.สุรพล เกษตรอนันต์",
    requesterEmail: "surapol.k@kku.ac.th",
    status: "SUBMITTED",
    fiscalYear: 2570,
    category: "ครุภัณฑ์การเกษตร",
    totalBudgetBaht: 2200000,
    quantity: 1,
    unit: "ระบบ",
    unitPriceBaht: 2200000,
    standardMatched: false,
    standardName: "โรงเรือนปลูกพืชระบบอัตโนมัติควบคุมอุณหภูมิและความชื้น",
    alertLevel: "CUSTOM_NON_STANDARD",
    createdAt: "2026-08-13T10:20:00Z",
    updatedAt: "2026-08-23T16:00:00Z",
  },
  {
    id: "req-035",
    code: "REQ-2570-035",
    title: "อากาศยานไร้คนขับเพื่อการเกษตรแม่นยำสูง ขนาดถังบรรจุ 30 ลิตร สำหรับงานวิจัยพืชไร่",
    faculty: "คณะเกษตรศาสตร์",
    department: "ศูนย์วิจัยเทคโนโลยีการเกษตร",
    requesterId: "emp-030",
    requesterName: "รศ.ดร.สุรพล เกษตรอนันต์",
    requesterEmail: "surapol.k@kku.ac.th",
    status: "DEPT_REVIEW",
    fiscalYear: 2570,
    category: "ครุภัณฑ์การเกษตร",
    totalBudgetBaht: 420000,
    quantity: 1,
    unit: "เครื่อง",
    unitPriceBaht: 420000,
    standardMatched: false,
    standardName: "โดรนเพื่อการเกษตรสำหรับฉีดพ่นและสำรวจสุขภาพพืช",
    alertLevel: "CUSTOM_NON_STANDARD",
    createdAt: "2026-08-24T11:40:00Z",
    updatedAt: "2026-08-25T09:15:00Z",
  },
  {
    id: "req-036",
    code: "REQ-2570-036",
    title: "เครื่องวิเคราะห์ธาตุอาหารและคุณภาพดินแบบพกพาภาคสนาม (Portable Soil Nutrient Analyzer)",
    faculty: "คณะเกษตรศาสตร์",
    department: "สาขาวิชาพืชศาสตร์และปฐพีศาสตร์",
    requesterId: "emp-030",
    requesterName: "รศ.ดร.สุรพล เกษตรอนันต์",
    requesterEmail: "surapol.k@kku.ac.th",
    status: "AI_ANALYZED",
    fiscalYear: 2570,
    category: "ครุภัณฑ์การเกษตร",
    totalBudgetBaht: 290000,
    quantity: 2,
    unit: "เครื่อง",
    unitPriceBaht: 145000,
    standardMatched: true,
    standardName: "เครื่องตรวจวิเคราะห์คุณสมบัติดินภาคสนาม",
    alertLevel: "GREEN_MATCH",
    createdAt: "2026-08-28T09:00:00Z",
    updatedAt: "2026-08-28T09:05:00Z",
  },

  // ==========================================
  // หมวดที่ 7: ครุภัณฑ์โฆษณาและเผยแพร่ (2 รายการ)
  // ==========================================
  {
    id: "req-037",
    code: "REQ-2570-037",
    title: "ชุดกล้องบันทึกวิดีโอระดับ 4K พร้อมระบบส่งสัญญาณไร้สาย สำหรับห้องสตูดิโอผลิตบทเรียนออนไลน์",
    faculty: "สำนักนวัตกรรมการเรียนการสอน",
    department: "ฝ่ายผลิตสื่อนวัตกรรมดิจิทัล",
    requesterId: "emp-031",
    requesterName: "ผศ.ดร.ปรารถนา ทรงคุณ",
    requesterEmail: "prartana.t@kku.ac.th",
    status: "APPROVED",
    fiscalYear: 2570,
    category: "ครุภัณฑ์โฆษณาและเผยแพร่",
    totalBudgetBaht: 480000,
    quantity: 2,
    unit: "ชุด",
    unitPriceBaht: 240000,
    standardMatched: true,
    standardName: "กล้องบันทึกภาพวิดีโอระบบดิจิทัลความละเอียด 4K",
    alertLevel: "GREEN_MATCH",
    createdAt: "2026-08-08T10:00:00Z",
    updatedAt: "2026-08-14T15:20:00Z",
  },
  {
    id: "req-038",
    code: "REQ-2570-038",
    title: "ชุดระบบไฟสตูดิโอ LED แบบควบคุมระยะไกลด้วยแอปพลิเคชันและโปรโตคอล DMX",
    faculty: "กองสื่อสารองค์กร",
    department: "งานผลิตสื่อและสารสนเทศ",
    requesterId: "emp-032",
    requesterName: "นายชวลิต มีลาภ",
    requesterEmail: "chawalit.m@kku.ac.th",
    status: "REVISED",
    fiscalYear: 2570,
    category: "ครุภัณฑ์โฆษณาและเผยแพร่",
    totalBudgetBaht: 210000,
    quantity: 1,
    unit: "ชุด",
    unitPriceBaht: 210000,
    standardMatched: true,
    standardName: "ชุดโคมไฟสตูดิโอ LED สตรีมมิ่ง",
    alertLevel: "AMBER_ALERT",
    createdAt: "2026-08-15T14:30:00Z",
    updatedAt: "2026-08-25T16:00:00Z",
    reviewComments: [
      {
        id: "comm-038-1",
        authorId: "emp-002",
        authorName: "นายประเสริฐ รักงาน",
        authorRole: "DEPT_VERIFIER",
        content: "สเปกมีระบุชื่อแบรนด์ระบบไฟชัดเจนในข้อ 2.4 ให้ปรับแก้เป็นคุณสมบัติเชิงหน้าที่ เช่น กำลังส่องสว่าง Lux และค่าความถูกต้องของสี CRI >= 96",
        action: "REQUEST_CHANGE",
        createdAt: "2026-08-25T16:00:00Z",
      },
    ],
  },

  // ==========================================
  // หมวดที่ 8: ครุภัณฑ์โรงงานและวิศวกรรม (2 รายการ)
  // ==========================================
  {
    id: "req-039",
    code: "REQ-2570-039",
    title: "เครื่องตัดเลเซอร์ไฟเบอร์ CNC สำหรับงานแปรรูปโลหะแผ่นและต้นแบบทางวิศวกรรม (CNC Fiber Laser Cutting Machine)",
    faculty: "คณะวิศวกรรมศาสตร์",
    department: "สาขาวิชาวิศวกรรมอุตสาหการ",
    requesterId: "emp-033",
    requesterName: "รศ.ดร.สุชาติ ภิญโญ",
    requesterEmail: "suchart.p@kku.ac.th",
    status: "SUBMITTED",
    fiscalYear: 2570,
    category: "ครุภัณฑ์โรงงานและวิศวกรรม",
    totalBudgetBaht: 3500000,
    quantity: 1,
    unit: "เครื่อง",
    unitPriceBaht: 3500000,
    standardMatched: false,
    standardName: "เครื่องตัดเลเซอร์ไฟเบอร์ระบบซีเอ็นซี",
    alertLevel: "CUSTOM_NON_STANDARD",
    createdAt: "2026-08-11T16:00:00Z",
    updatedAt: "2026-08-23T14:00:00Z",
  },
  {
    id: "req-040",
    code: "REQ-2570-040",
    title: "เครื่องพิมพ์ 3 มิติระบบ Industrial SLA ความละเอียดสูงสำหรับชิ้นงานต้นแบบทางการแพทย์และสถาปัตยกรรม",
    faculty: "คณะสถาปัตยกรรมศาสตร์",
    department: "สาขาวิชาการออกแบบอุตสาหกรรม",
    requesterId: "emp-008",
    requesterName: "ผศ.ดร.กานต์พิชชา ภักดี",
    requesterEmail: "karnpitcha.p@kku.ac.th",
    status: "REJECTED",
    fiscalYear: 2570,
    category: "ครุภัณฑ์โรงงานและวิศวกรรม",
    totalBudgetBaht: 1600000,
    quantity: 1,
    unit: "เครื่อง",
    unitPriceBaht: 1600000,
    standardMatched: false,
    standardName: "เครื่องพิมพ์สามมิติระบบเรซินความละเอียดสูง",
    alertLevel: "CUSTOM_NON_STANDARD",
    createdAt: "2026-08-02T10:00:00Z",
    updatedAt: "2026-08-10T11:00:00Z",
    reviewComments: [
      {
        id: "comm-040-1",
        authorId: "emp-003",
        authorName: "ศ.ดร.วิโรจน์ วิเศษ",
        authorRole: "APPROVER",
        content: "ไม่อนุมัติเนื่องจากมีครุภัณฑ์เครื่องพิมพ์ 3 มิติที่มีสมรรถนะใกล้เคียงกันเปิดให้บริการอยู่ที่ศูนย์ Maker Space ของมหาวิทยาลัยแล้ว แนะนำให้ทำความร่วมมือเพื่อใช้ทรัพยากรร่วมกัน",
        action: "REJECT",
        createdAt: "2026-08-10T11:00:00Z",
      },
    ],
  },
];

/**
 * Helper function to synthesize full Form 8 Sections and Step 6 Neutral Specs
 * for every single proposal to ensure 100% data richness.
 */
export function populateFullDetails(prop: BudgetProposal): BudgetProposal {
  if (prop.form8Sections && prop.neutralSpec && prop.aiAnalysis) {
    return prop;
  }

  const p = prop.unitPriceBaht;
  const isComputer = prop.category.includes("คอมพิวเตอร์");
  const isSci = prop.category.includes("วิทยาศาสตร์");
  const isMed = prop.category.includes("การแพทย์");

  const form8Sections: KKUBudgetForm8Sections = {
    section1BasicInfo: {
      agency: `${prop.faculty} / ${prop.department}`,
      itemName: `${prop.title} จำนวน ${prop.quantity} ${prop.unit}`,
      quantity: prop.quantity,
      unit: prop.unit,
      budgetBaht: prop.totalBudgetBaht,
      unitPriceBaht: prop.unitPriceBaht,
      plan: "แผนงานจัดการศึกษาระดับอุดมศึกษา",
      subPlan: "แผนงานย่อยส่งเสริมการวิจัย นวัตกรรม และความเป็นเลิศทางวิชาการ",
      project: `โครงการพัฒนาขีดความสามารถด้านโครงสร้างพื้นฐานและนวัตกรรม ประจำปีงบประมาณ ${prop.fiscalYear}`,
      objective: `เพื่อใช้ในการเรียนการสอน การวิจัย และการบริการวิชาการแก่สังคมของ ${prop.department}`,
      equipmentType: prop.category,
      procurementType: "จัดซื้อจัดจ้างตามระเบียบกระทรวงการคลังว่าด้วยการจัดซื้อจัดจ้างและการบริหารพัสดุภาครัฐ พ.ศ. 2560",
      sCurve: isComputer ? "Digital & AI Technology" : isMed ? "Medical & Healthcare Hub" : "High-Value Agriculture & Innovation",
      sdgs: ["SDG 4 (Quality Education)", "SDG 9 (Industry, Innovation, and Infrastructure)"],
    },
    section2Necessity: {
      details: `เนื่องจาก ${prop.department} ${prop.faculty} มีภารกิจในการจัดการเรียนการสอนและโครงการวิจัยที่มีความจำเป็นต้องใช้ ${prop.title} โดยอุปกรณ์เดิมชำรุดและล้าสมัยไม่สามารถรองรับมาตรฐานปัจจุบันได้`,
      installationLocation: `อาคารปฏิบัติการ ${prop.faculty} มหาวิทยาลัยขอนแก่น`,
      targetCurriculum: "หลักสูตรระดับปริญญาตรี โท เอก และงานวิจัยเฉพาะทาง",
      userCount: prop.quantity > 5 ? prop.quantity * 25 : 80,
      impactIfNotFunded: "ส่งผลกระทบต่อความล่าช้าในการส่งมอบงานวิจัย และทำให้นักศึกษาขาดโอกาสในการฝึกทักษะด้วยเครื่องมือมาตรฐานสากล",
      urgency: "มีความจำเป็นเร่งด่วนเพื่อรองรับการเปิดภาคการศึกษาและการตรวจประเมินคุณภาพหลักสูตรระดับสากล",
    },
    section3AttachmentsChecklist: {
      photos: true,
      specPdf: true,
      quotationsPdf: true,
      feasibilityStudyRequired: prop.totalBudgetBaht >= 10000000,
    },
    section4QuotationComparison: {
      vendor1: { name: "บริษัท ซิลิคอน ซิสเต็มส์ แอนด์ เซอร์วิส จำกัด", price: Math.round(p * 0.98) },
      vendor2: { name: "บริษัท ดาต้า อินโนเวชั่น ซัพพลาย จำกัด", price: p },
      vendor3: { name: "บริษัท ไทย อินสตรูเมนท์ เทคโนโลยี จำกัด", price: Math.round(p * 1.04) },
      selectedVendorIndex: 1,
      notes: "ใช้ราคาต่ำสุดจากใบเสนอราคาของผู้ประกอบการที่มีคุณสมบัติตรงตามข้อกำหนดทางเทคนิคครบถ้วน",
    },
    section5StandardComparison: {
      ref1: prop.standardMatched ? "บัญชีราคามาตรฐานครุภัณฑ์ สำนักงบประมาณ / กระทรวง DE (ฉบับปีงบประมาณ 2569)" : "ราคาจากการสืบราคาตลาดตามใบเสนอราคา 3 ราย",
      ref2: "แนวทางราคากลางครุภัณฑ์ มหาวิทยาลัยขอนแก่น (2570)",
      notes: prop.alertLevel === "GREEN_MATCH"
        ? "วงเงินที่ขอเสนอสอดคล้องตามเกณฑ์ราคากลางมาตรฐาน"
        : prop.alertLevel === "AMBER_ALERT"
        ? `วงเงินที่ขอเสนอสูงกว่าเกณฑ์ราคากลางเนื่องจากต้องการสมรรถนะเฉพาะทางสำหรับงานวิจัยขั้นสูง`
        : "เป็นรายการนอกบัญชีมาตรฐานครุภัณฑ์ ได้ดำเนินการสืบราคาตลาดจากผู้ประกอบการ 3 รายแล้ว",
    },
    section6Readiness: {
      procurementReadiness: "มีความพร้อมจัดทำร่างขอบเขตของงาน (TOR) และแต่งตั้งคณะกรรมการตรวจรับพัสดุทันทีที่ได้รับการจัดสรรงบประมาณ",
      contractSigning: "สามารถลงนามในสัญญาจัดซื้อจัดจ้างได้ภายใน 30 วันทำการหลังประกาศผู้ชนะ",
      installationDelivery: "พร้อมตรวจรับและติดตั้งใช้งานได้ภายใน 45 วันหลังลงนามสัญญา",
    },
    section7SpecSummary: {
      generalSpec: `เป็น ${prop.title} คุณภาพมาตรฐานสากล ผลิตจากโรงงานที่ได้รับมาตรฐาน ISO 9001 หรือเทียบเท่า`,
      technicalSpec: isComputer
        ? "หน่วยประมวลผลประสิทธิภาพสูง RAM DDR5 ความเร็วสูง SSD NVMe ความเร็วสูง พร้อมพอร์ตเชื่อมต่อครบชุด หรือเทียบเท่า"
        : isSci
        ? "ระบบควบคุมดิจิทัลความแม่นยำสูง วัสดุทนทานต่อสารเคมีและไอระเหย พร้อมระบบเซนเซอร์วัดค่าตามมาตรฐานสากล หรือเทียบเท่า"
        : "อุปกรณ์และระบบควบคุมมาตรฐานการแพทย์/การศึกษา ความเที่ยงตรงสูง พร้อมระบบความปลอดภัยระดับสากล หรือเทียบเท่า",
      accessories: "อุปกรณ์ต่อพ่วง คู่มือการใช้งานภาษาไทย/อังกฤษ และการรับประกันบริการ On-site ไม่น้อยกว่า 2-3 ปี",
    },
    section8AdditionalNotes: "รายการคำของบประมาณนี้ผ่านความเห็นชอบจากคณะกรรมการประจำคณะ และสอดคล้องกับยุทธศาสตร์การพัฒนามหาวิทยาลัยขอนแก่น",
  };

  const neutralSpec: Step6NeutralSpecResult = {
    specTitle: `ร่างขอบเขตของงานและคุณลักษณะเฉพาะ (TOR): ${prop.title}`,
    disclaimer: "เอกสารนี้เป็นร่างคุณลักษณะเฉพาะเพื่อประกอบการพิจารณา มิใช่สเปกสำเร็จรูปสำหรับการจัดซื้อจัดจ้างโดยไม่ผ่านความเห็นชอบของคณะกรรมการ",
    categories: [
      {
        categoryName: "1. คุณลักษณะทั่วไป (General Requirements)",
        items: [
          `เป็น ${prop.title} ของใหม่ไม่เคยผ่านการใช้งานมาก่อน`,
          "ตัวเครื่องและอุปกรณ์ประกอบทั้งหมดได้รับการรับรองมาตรฐานสากล เช่น ISO, CE, FCC หรือ มอก. หรือเทียบเท่า",
          "รองรับการใช้งานกับระบบไฟฟ้ามาตรฐาน 220V 50Hz ของประเทศไทย",
        ],
      },
      {
        categoryName: "2. คุณลักษณะเฉพาะเชิงหน้าที่ (Functional & Technical Specifications)",
        items: [
          `มีสมรรถนะการทำงานสอดคล้องตามวัตถุประสงค์การใช้งานของ ${prop.department}`,
          "มีระบบควบคุมการทำงานแบบดิจิทัลพร้อมหน้าจอแสดงผลสถานะการทำงานแบบ Real-time",
          "รองรับการเชื่อมต่อและโอนถ่ายข้อมูลผ่านพอร์ตมาตรฐานสากล หรือเทียบเท่า",
        ],
      },
      {
        categoryName: "3. การรับประกัน การฝึกอบรม และบริการหลังการขาย (Warranty & Services)",
        items: [
          "มีการรับประกันผลิตภัณฑ์และการตรวจซ่อม ณ สถานที่ติดตั้ง (On-site Service) ทุกชิ้นส่วนเป็นระยะเวลาไม่น้อยกว่า 2 ปี",
          "ผู้เสนอราคาต้องจัดให้มีการฝึกอบรมการใช้งานและการบำรุงรักษาขั้นต้นแก่บุคลากรผู้รับผิดชอบไม่น้อยกว่า 1 วันทำการ",
          "มีคู่มือการใช้งานและเอกสารการบำรุงรักษาภาษาไทยและภาษาอังกฤษอย่างละ 1 ชุด",
        ],
      },
    ],
    brandLinterIssues: [],
  };

  const aiAnalysis: Full6StepAnalysis = {
    step1: {
      itemCategory: prop.category,
      rawItemName: prop.title,
      objective: form8Sections.section1BasicInfo.objective,
      quantity: prop.quantity,
      unit: prop.unit,
      totalProposedBudget: prop.totalBudgetBaht,
      unitProposedPrice: prop.unitPriceBaht,
      urgencyReason: form8Sections.section2Necessity.urgency,
      targetDepartment: `${prop.department} ${prop.faculty}`,
    },
    step2: {
      isMatched: prop.standardMatched,
      matchStatus: prop.standardMatched ? "matched" : "non_standard",
      rawName: prop.title,
      recommendedStandardName: prop.standardName || prop.title,
      standardUnitPrice: prop.standardMatched ? prop.unitPriceBaht : null,
      evidence: prop.standardMatched
        ? {
            source: "บัญชีราคามาตรฐานครุภัณฑ์ สำนักงบประมาณ / กระทรวง DE (ฉบับ พ.ค. 2569)",
            description: prop.title,
          }
        : null,
      comparisonNotes: prop.standardMatched
        ? "รายการตรงตามบัญชีราคามาตรฐานครุภัณฑ์ภาครัฐ"
        : "รายการนอกบัญชีมาตรฐาน ต้องใช้ราคาอ้างอิงจากการสืบราคาตลาด 3 ราย",
    },
    step3: {
      itemName: prop.standardName || prop.title,
      sources: [
        {
          sourceId: "budget_bureau",
          sourceName: "สำนักงบประมาณ",
          found: prop.standardMatched,
          unitPrice: prop.standardMatched ? prop.unitPriceBaht : undefined,
          docRef: "บัญชีราคามาตรฐานครุภัณฑ์ สำนักงบประมาณ ฉบับ เม.ย. 2569",
        },
        {
          sourceId: "de_ministry",
          sourceName: "กระทรวงดิจิทัลเพื่อเศรษฐกิจและสังคม",
          found: isComputer,
          unitPrice: isComputer ? prop.unitPriceBaht : undefined,
          docRef: "เกณฑ์ราคากลางและคุณลักษณะพื้นฐาน พ.ค. 2569",
        },
        {
          sourceId: "kku_standard",
          sourceName: "มหาวิทยาลัยขอนแก่น",
          found: true,
          unitPrice: prop.unitPriceBaht,
          docRef: "แนวทางราคากลางครุภัณฑ์ มข. ประจำปี 2570",
        },
        {
          sourceId: "historical_quotation",
          sourceName: "ราคาตลาด / ใบเสนอราคา 3 ราย",
          found: true,
          unitPrice: prop.unitPriceBaht,
          docRef: "ใบเสนอราคา บจก. ซิลิคอน ซิสเต็มส์ แอนด์ เซอร์วิส (ราคาต่ำสุด)",
        },
      ],
      minStandardPrice: prop.unitPriceBaht,
      maxStandardPrice: prop.unitPriceBaht,
      benchmarkVarianceBaht: prop.alertLevel === "AMBER_ALERT" ? Math.round(prop.unitPriceBaht * 0.15) : 0,
      benchmarkVariancePercent: prop.alertLevel === "AMBER_ALERT" ? 15.0 : 0.0,
    },
    step4: {
      alertLevel: prop.alertLevel,
      statusLabel:
        prop.alertLevel === "GREEN_MATCH"
          ? "Green Match: ขอตั้งงบประมาณสอดคล้องตามราคามาตรฐาน"
          : prop.alertLevel === "AMBER_ALERT"
          ? "Budget Alert: วงเงินที่ขอสูงกว่าราคามาตรฐานอ้างอิง"
          : "Non-Standard: รายการนอกบัญชีราคามาตรฐาน",
      proposedUnitPrice: prop.unitPriceBaht,
      standardUnitPrice: prop.unitPriceBaht,
      priceDifference: prop.alertLevel === "AMBER_ALERT" ? Math.round(prop.unitPriceBaht * 0.15) : 0,
      differencePercentage: prop.alertLevel === "AMBER_ALERT" ? 15.0 : 0.0,
      reasoning: form8Sections.section5StandardComparison.notes,
      guidance: [
        "ตรวจสอบความถูกต้องของรายการและความคุ้มค่าทางวิชาการ",
        "แนบใบเสนอราคาจากผู้ประกอบการ 3 รายเพื่อยืนยันราคาตลาด",
        "จัดทำร่าง TOR ด้วยถ้อยคำที่เป็นกลาง ไม่ระบุยี่ห้อหรือรุ่นเฉพาะเจาะจง",
      ],
      requiredAttachments: {
        threeQuotationsRequired: prop.alertLevel !== "GREEN_MATCH",
        academicJustificationRequired: prop.alertLevel === "AMBER_ALERT",
        feasibilityStudyRequired: prop.totalBudgetBaht >= 10000000,
        functionalSpecRequired: true,
      },
    },
    step5: form8Sections,
    step6: neutralSpec,
    completedAt: prop.createdAt,
  };

  return {
    ...prop,
    form8Sections,
    neutralSpec,
    aiAnalysis,
  };
}

export const ALL_40_MOCK_PROPOSALS: BudgetProposal[] = MOCK_PROPOSALS.map(populateFullDetails);
